dark_dir: "/astro/sveash/darks/*/*corrtag*fits"
solar_dir: "/astro/sveash/solar_data/*txt"
dbsettings: 
    "cos_dark": 
        dbtype: "sqlite"
        loc: "/astro/sveash/cos_dark/cos_dark.db"
    "dark_events":
        dbtype: "mysql"
        dbname: "hstcal"
        host: "PLTANMYSQL"
        port: "3313"
        user: "jotaylor"
